the other kind of libraries

```{r,cache=T}
library(tidyverse)
library(ggrepel)
library(pheatmap)
```

```{r,cache=T}
datar <- read_csv("RESULTS_V2_181209_Magnetic Media Survey - Some Calculations.csv") %>%
    filter(complete.cases(.)) 

pdatar <- datar %>% 
    gather(variable,value,-`Institution-CollectionKey`) %>%
    mutate(value=as.numeric(value)) 

risk_factors <- read_tsv("risk_factors.tsv") %>%
    mutate(Risk=factor(Risk,levels=c("Low","Moderate","High","Very High","Extremely High")))
```

```{r,cache=T}
totals_and_risks <- pdatar %>% filter(variable!="Total Items") %>%
    group_by(variable) %>% summarize(Total=sum(value,na.rm=T)) %>%
    arrange(Total) %>%
    mutate(Format=factor(variable,levels=variable)) %>%
    left_join(risk_factors,by="Format") %>%
    select(-Quantity)

totals_and_risks
```

```{r,fig.height=9,fig.width=9,cache=T}
g<- totals_and_risks%>%
    filter(Total>0,!is.na(Risk))%>%
    ggplot()+theme_bw()+
    aes(x=Risk,y=Total)+
    theme(axis.text.x=element_text(angle=90))+
    geom_label_repel(aes(label=Format))+
    ylab("Total items across survey")+
    xlab("")+
    ggtitle("Total counts of high risk magnetic media")
g
```


```{r,fig.height=5,fig.width=7,cache=T}
g <- pdatar %>%
    mutate(variable=factor(variable,levels=arrange(totals_and_risks,-Total)$Format)) %>%
    filter(variable!="Total Items")%>%
    filter(value>0)%>%
    ggplot()+theme_bw()+
    geom_boxplot(outlier.alpha=0)+
    geom_dotplot(binaxis="y",stackdir="center",dotsize=1.0,alpha=0.5,binwidth=0.05)+
    aes(x=variable,y=value)+
    scale_y_log10(breaks=c(10,100,1000,10000,1000000))+
    theme(axis.text.x=element_text(angle=90))+
    ylab("Estimated number of items in collection of that format")+
    xlab("Format")
g
```


```{r,fig.height=5,fig.width=7,cache=T}
g <- pdatar %>%
    spread(variable,value) %>%
    gather(variable,value,-`Institution-CollectionKey`,-`Total Items`) %>%
    mutate(proportion=value/`Total Items`) %>%
    mutate(variable=factor(variable,levels=arrange(totals_and_risks,-Total)$Format)) %>%
    filter(variable!="Total Items")%>%
    filter(proportion>0)%>%
    ggplot()+theme_bw()+
    geom_boxplot(outlier.alpha=0)+
    geom_dotplot(binaxis="y",stackdir="center",alpha=0.5,binwidth=0.01)+
    aes(x=variable,y=proportion)+
    theme(axis.text.x=element_text(angle=90))+
    ylab("Fraction of collection in that format")+
    xlab("Format")
g
```

```{r,cache=T}
matrix_by_inst <- as.matrix(datar[,-c(1,2)])
rownames(matrix_by_inst) <- datar[,1][[1]]
cluster_inst <- hclust(dist(scale(matrix_by_inst))) 
matrix_by_media <- t(as.matrix(datar[,-c(1,2)]))
cluster_media <- hclust(dist(scale(matrix_by_media)))
```

```{r,cache=T}
pca_media <- prcomp(t(matrix_by_media[apply(matrix_by_media,1,sum)>0,]),center=T,scale=T)
pca_inst <- prcomp(t(matrix_by_inst[apply(matrix_by_inst,1,sum)>0,] ),center=T,scale=T)

media_pca_plot <- pca_media$rotation %>% 
    {bind_cols(tibble(Format=rownames(.)),as.tibble(.))} %>%
    select(Format,PC1,PC2,PC3,PC4,PC5,PC6) %>% 
    ggplot()+theme_bw()+
    aes(label=Format)+
    geom_label_repel()
media_pca_plot + aes(x=PC1,y=PC2)
media_pca_plot + aes(x=PC3,y=PC4)
media_pca_plot + aes(x=PC5,y=PC6)

inst_pca_plot <- pca_inst$rotation %>% 
    {bind_cols(tibble(Format=rownames(.)),as.tibble(.))} %>%
    select(Format,PC1,PC2,PC3,PC4,PC5,PC6) %>% 
    ggplot()+theme_bw()+
    aes(label=Format)+
    geom_label_repel()
inst_pca_plot + aes(x=PC1,y=PC2)
inst_pca_plot + aes(x=PC3,y=PC4)
inst_pca_plot + aes(x=PC5,y=PC6)
```

```{r,fig.height=9,fig.width=9,cache=T}

row_ann <- data.frame(
    Collection=str_c("C_",as.character(rownames(matrix_by_inst)[cluster_inst$order]))
    )
rownames(row_ann) <- as.character(row_ann[[1]])

col_ann <- data.frame(Format=rownames(matrix_by_media)[cluster_media$order]) %>%
    left_join(totals_and_risks,by="Format") %>% select(-variable) %>%
    rename(`Total Items`=Total,`Format Risk`=Risk) %>%
    select(-`Total Items`)
rownames(col_ann) <- col_ann[[1]]
col_ann <- col_ann %>% select(-Format)

count_palette <- c("#FFFFFF",
    colorRampPalette((RColorBrewer::brewer.pal(n=7,name="YlGnBu")))(99)
    )

g <- pheatmap( log10(datar[,-c(1,2)]+400),
    color=count_palette,
    correlation_distance_rows="pearson",
    correlation_distance_cols="pearson",
    legend_breaks=log10(c(10,100,1000,3000,1e4,2.5e4,5e4)),
    legend_labels=c(10,100,1000,3000,1e4,2.5e4,5e4),
    cluster_rows=cluster_inst,
    cluster_cols=cluster_media,
    show_rownames=F,show_colnames=T,
    #annotation_row=row_ann,
    annotation_col=col_ann,
    annotation_legend=T)
g
```


```{r,fig.height=9,fig.width=9,cache=T}

valz <- log10(unlist(datar[,-c(1,2)])+1)

col_ann <- data.frame(Format=rownames(matrix_by_media)[cluster_media$order]) %>%
    left_join(totals_and_risks,by="Format") %>% select(-variable) %>%
    rename(`Total Items`=Total,`Format Risk`=Risk) %>%
    select(-`Total Items`)
rownames(col_ann) <- col_ann[[1]]
col_ann <- col_ann %>% select(-Format)

counts_legend <- HeatmapAnnotation(
    heatmap_legend_param = list(
        title = "Item counts", 
        at=log10(c(10,1000,1e4,5e4)),
        labels=c(10,1000,1e4,5e4),
        heatmap_legend_side="bottom"
        )
    )

risk_annotation <- HeatmapAnnotation(
    `Format Risk`=col_ann$`Format Risk`,
    col=list(`Format Risk`=c(
            `Extremely High`="#7b3294",`Very High`="#c2a5cf",
            `High`="#a6dba0",`Moderate`="#008837"
    )   )   )
the_heatmap <- Heatmap(
    log10(datar[,-c(1,2)]+1),
    col=colorRamp2(c(min(valz),median(valz),max(valz)),c("#ffffff", "#fefefe", "#000000")),
    top_annotation=risk_annotation,
    heatmap_legend_param = list(
        title = "Item counts",
        at=log10(c(10,1000,1e4,5e4)),
        labels=c(10,1000,1e4,5e4),
        legend_height = unit(6, "cm")
        )
    )
ht_list <- the_heatmap 
g <- draw(ht_list, heatmap_legend_side = "right", annotation_legend_side = "right")
g

png("heatmap.png")
g
dev.off()


count_palette <- c("#FFFFFF",
    colorRampPalette((RColorBrewer::brewer.pal(n=7,name="YlGnBu")))(99)
    )

g <- pheatmap( log10(datar[,-c(1,2)]+400),
    color=count_palette,
    correlation_distance_rows="pearson",
    correlation_distance_cols="pearson",
    legend_breaks=log10(c(10,100,1000,3000,1e4,2.5e4,5e4)),
    legend_labels=c(10,100,1000,3000,1e4,2.5e4,5e4),
    cluster_rows=cluster_inst,
    cluster_cols=cluster_media,
    show_rownames=F,show_colnames=T,
    #annotation_row=row_ann,
    annotation_col=col_ann,
    annotation_legend=T)
g
```





